// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lcqrwhnpscchimjqysau.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxjcXJ3aG5wc2NjaGltanF5c2F1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzNDMyNzcsImV4cCI6MjA2MDkxOTI3N30.sMTduMkGxUTbEFnnPvkpUlEeQ3yz96_mlzD_XGWEj0U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);