
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lcqrwhnpscchimjqysau.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxjcXJ3aG5wc2NjaGltanF5c2F1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzNDMyNzcsImV4cCI6MjA2MDkxOTI3N30.sMTduMkGxUTbEFnnPvkpUlEeQ3yz96_mlzD_XGWEj0U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create client with improved configuration
export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
    },
    global: {
      fetch: fetch,
      headers: { 'x-client-info': 'kimcom-security-react' },
    },
    // Add proper error handling for fetch operations
    realtime: {
      params: {
        eventsPerSecond: 10
      }
    },
    db: {
      schema: 'public'
    }
  }
);

// Helper function to check database connection
export const checkDatabaseConnection = async () => {
  try {
    const { data, error } = await supabase.from('products').select('count', { count: 'exact', head: true });
    
    if (error) {
      console.error("Database connection test failed:", error);
      return false;
    } else {
      console.log("Database connection test successful");
      return true;
    }
  } catch (err) {
    console.error("Database connection test exception:", err);
    return false;
  }
};
